FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

# הפקודה שמריצה את האפליקציה של Streamlit
CMD ["streamlit", "run", "graph_viewer.py", "--server.port=8501", "--server.address=0.0.0.0"]
